repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v2.5.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
- repo: https://github.com/python/black
  rev: 19.10b0
  hooks:
  - id: black
    language_version: python3
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies: ['flake8-bugbear==20.1.4']
- repo: https://github.com/timothycrosley/isort
  rev: 4.3.21-2
  hooks:
  - id: isort
    language_version: python3
    types: [python]
